In [1]:
import control as ctrl
import numpy as np

## Transformación de función transferencia a espacio de estados

Supongamos que tenemos la siguiente función transferencia:

In [2]:
G=ctrl.tf([1,1],[1,2,3])
G


    s + 1
-------------
s^2 + 2 s + 3

De los apuntes de teoría podemos escribir una representación de espacios de estados en la forma canónica de controlabilidad que tendrá el mismo comportamiento externo de $G$ de la siguiente manera :

In [3]:
Ac=np.matrix([[-2, -3],[1,0]])
Ac

matrix([[-2, -3],
        [ 1,  0]])

Antes de seguir, verificamos que los polos de $G$ sean los autovalores de $Ac$

In [4]:
G.pole()

array([-1.+1.41421356j, -1.-1.41421356j])

In [5]:
np.linalg.eigvals(Ac)

array([-1.+1.41421356j, -1.-1.41421356j])

Ahora definimos el resto de las matrices

In [6]:
Bc=np.matrix("1;0")
Bc

matrix([[1],
        [0]])

In [7]:
Cc=np.matrix("1 1")
Cc

matrix([[1, 1]])

In [8]:
Dc=0

Vamos ahora a definir un sistema $sys$ que se comporte igual que $G$

In [9]:
sys_c=ctrl.ss(Ac,Bc,Cc,Dc)

Si $sys$ tiene los mismos polos, los mismos ceros y la misma ganancia en estado estacionario, entonces se comportará igual que $G$.

In [10]:
sys_c.pole()

array([-1.+1.41421356j, -1.-1.41421356j])

In [11]:
sys_c.zero()

array([-1.+0.j])

In [12]:
sys_c.dcgain()

array(0.33333333)

In [13]:
G.dcgain()

array(0.33333333)

Por lo tanto podemos ver que la función transfewrencia de $sys$ será la misma que la de $G$. Es decir, $sys$ se comporta externamente igual que $G$. Verificamos

In [14]:
ctrl.tf(sys_c)


    s + 1
-------------
s^2 + 2 s + 3

Vamos ahora a definir el sistema en espacio de estados, que se comporte como $G$ en la forma canónica de observabilidad. De la teoría sabemos que:

In [16]:
Ao=Ac.T
Bo=Cc.T
Co=Bc.T
Do=Dc

In [17]:
sys_o=ctrl.ss(Ao,Bo,Co,Do)

In [18]:
sys_o.pole()

array([-1.+1.41421356j, -1.-1.41421356j])

In [19]:
sys_o.zero()

array([-1.+0.j])

In [20]:
sys_o.dcgain()

array(0.33333333)

In [21]:
ctrl.tf(sys_o)


    s + 1
-------------
s^2 + 2 s + 3

In [22]:
ctrl.tf(sys_o)


    s + 1
-------------
s^2 + 2 s + 3

El módulo de control de Python puede transformar una función transferencia a una forma de estados (no necesariameinte en alguna forma canónica). Esto se hace:

In [23]:
sys=ctrl.ss(G)

Además Python puede transformar un sistema en espacio de estados a alguna de las formas canónicas.

Por ejemplo para escribir $sys$ (que está ahora en espacio de estados) en su forma canónica de controlabilidad podemos hacer

In [24]:
ctrl.canonical_form(sys, 'reachable')

(A = [[-2. -3.]
  [ 1.  0.]]
 
 B = [[1.]
  [0.]]
 
 C = [[1. 1.]]
 
 D = [[0.]],
 matrix([[ 1.00000000e+00, -2.22044605e-16],
         [-0.00000000e+00, -1.00000000e+00]]))

No tar que esta función necesita como primer argumento un sistema de espacios de estados.

Si queremos la forma canónica de observabilidad podemos hacer:

In [25]:
ctrl.canonical_form(sys, 'observable')

(A = [[-2.  1.]
  [-3.  0.]]
 
 B = [[1.]
  [1.]]
 
 C = [[1. 0.]]
 
 D = [[0.]],
 matrix([[ 1., -1.],
         [ 1.,  1.]]))

Existe otra forma canónica de represetanción en espacio de estados que se la conoce como froma canónica modal. Esta la podemos obtener haciendo:

In [26]:
ctrl.canonical_form(sys, 'modal')

(A = [[-1.          1.41421356]
  [-1.41421356 -1.        ]]
 
 B = [[ 1.15470054]
  [-0.81649658]]
 
 C = [[ 0.57735027 -0.40824829]]
 
 D = [[0.]],
 matrix([[0.8660254 , 0.        ],
         [0.28867513, 0.40824829]]))

Esta forma canónica lo que haces es aislar los modos unos de otros. Es decir cada variables de estado aparece en la diagonal. Sin embargo, como vemos en este caso, no tenemos una forma diagonal de la matriz $A$. Esto sucede por que hay casos que no se puede o no se dease aislarlos:
- en caso de que se tengan autovales complejos conjugados, no se aislan para lograr tener una matriz $A$, $B$ y $C$ a coficiente reales.
- en caso de que sean multiples no se pueden aislar por que tienen el mismo autovector y no se pueden usar estos para la transformación. Para estos casos se utiliza la forma de Jordan (no se dará en este curso).

Vamos a ver otro ejemplo:

In [27]:
s=ctrl.tf('s')
G2 = 1/((s+1)*(s+2)*(s+3))
G2


          1
----------------------
s^3 + 6 s^2 + 11 s + 6

Vemos que esta función trnasferencia tiene los polos en -1, -2 y -3. Transformemosla a espacio de estados usando la función `ss`.

In [28]:
sys2 = ctrl.ss(G2)
sys2

A = [[ -6.    1.1  -0.6]
 [-10.    0.    0. ]
 [  0.   -1.    0. ]]

B = [[-1.]
 [ 0.]
 [ 0.]]

C = [[ 0.   0.  -0.1]]

D = [[0.]]

Veamos al sistema en su forma canónica de controlabilidad.

In [29]:
ctrl.canonical_form(sys2, 'reachable')

(A = [[ -6. -11.  -6.]
  [  1.   0.   0.]
  [  0.   1.   0.]]
 
 B = [[1.]
  [0.]
  [0.]]
 
 C = [[-6.25762068e-18 -6.30808537e-17  1.00000000e+00]]
 
 D = [[0.]],
 matrix([[-1.00000000e+00,  6.86319688e-17,  2.44249065e-16],
         [ 3.55271368e-17,  1.00000000e-01, -0.00000000e+00],
         [-6.25762068e-18,  6.30808537e-18, -1.00000000e-01]]))

Ahora veamoslo en la forma canónica de observabilidad

In [30]:
ctrl.canonical_form(sys2, 'observable')

(A = [[ -6.   1.   0.]
  [-11.   0.   1.]
  [ -6.   0.   0.]]
 
 B = [[0.]
  [0.]
  [1.]]
 
 C = [[1. 0. 0.]]
 
 D = [[0.]],
 matrix([[ 0.0000000e+00, -4.4408921e-18, -1.0000000e-01],
         [-0.0000000e+00,  1.0000000e-01, -6.0000000e-01],
         [-1.0000000e+00,  6.0000000e-01, -1.1000000e+00]]))

Finalmente obtengamos la forma conónica modal:

In [31]:
sys2_m, _=ctrl.canonical_form(sys2, 'modal')

In [32]:
sys2_m.A

matrix([[-1.00000000e+00, -4.44089210e-16,  6.66133815e-16],
        [ 0.00000000e+00, -2.00000000e+00,  1.77635684e-15],
        [ 8.88178420e-16, -1.77635684e-15, -3.00000000e+00]])

Notar:
- La función `canoincal_form` devuelve un sistema en la forma canónica solicitada y la amtriz de trnasformación necesaria para obtenerlo
- En la diagonal tenmos los modos del sistema (polos de G o autovalores de A)
- Fuera de la diagonal tenemos ceros o valores muy cercanos a ceros (debido a problemas numericos en el cálculo)


Verificamos el resto de las matrices:

In [33]:
sys2_m.B

matrix([[ -7.08872344],
        [-22.71563338],
        [ 16.43928222]])

In [34]:
sys2_m.C

matrix([[-0.07053456,  0.04402255,  0.03041495]])

In [35]:
sys2_m.D


matrix([[0.]])

En esta forma canónica, la matriz B como la conexión de la entrada con el modo del sistema . Y de forma análoga a la mariz C como la conexi;on del modo con la salida del sistema.

## Ejemplo de conexión de sistemas

In [36]:
G1=ctrl.tf(1,[1,1])
G2=ctrl.tf([1,1],[1,2])

Podemos ver que G1 tiene un polo en -1 y G2 tiene un polo en -2 y un cero en -1.

Ahora supogamos que queremos un nuevo sistema que:
- conecta la salida de G1 con la entrada de G2
- la salida es la salida de G2
- la entrada es la entrada de G1

Para eso vamos a usar una función que se llama `connect`. Esta utiliza sistemas en espacio de estados, entonces hacemos:

In [37]:
sys1 = ctrl.ss(G1)
sys2= ctrl.ss(G2)

Y lueog relizamos las conexiones:

In [38]:
sys_c = ctrl.connect(ctrl.append(sys1, sys2),[[2,1]],[1],[2])
sys_c

A = [[-1.  0.]
 [ 1. -2.]]

B = [[1.]
 [0.]]

C = [[ 1. -1.]]

D = [[0.]]

Analizamos  los polos y ceros del sistema ya interconectado 

In [39]:
sys_c.pole()

array([-2., -1.])

In [40]:
sys_c.zero()

array([-1.+0.j])

Vemos que el sistema conserva los mismos polos y los mismos ceros que el original, lo cual era de esperarse, ya que su función transferencia sería G1*G2

Obtngamos la forma canónica de controlabilidad del sistema

In [41]:
ctrl.canonical_form(sys_c, 'reachable')


(A = [[-3. -2.]
  [ 1.  0.]]
 
 B = [[1.]
  [0.]]
 
 C = [[1. 1.]]
 
 D = [[0.]],
 matrix([[ 1., -2.],
         [ 0.,  1.]]))

Podemos ver que las matrices A, B, C y D coinciden con lo visto en teoría.

Ahora obtengamos la forma canónica de observabilidad:

In [42]:
ctrl.canonical_form(sys_c, 'observable')

ValueError: Transformation matrix singular to working precision.

Podemos ver que este sistema no puede ser escrito en su forma canónica de observabilidad. Esto sucede por que el sistema no es observable.

La interptertación se da por que un sistema observable necesita tener evidencia de lo que sucede con cada modo a la salida. Como el modo en -1 se ve completamente tapado por el cero en esa misma frecuencia este sistema no es observable por que no tiene niguna evidencia del modo en -1 a la salida del mismo.

Ahora hagamos la conexión al revez (primero G1 y luego G2):

In [44]:
sys_o = ctrl.connect(ctrl.append(sys1, sys2),[[1,2]],[2],[1])
sys_o

A = [[-1. -1.]
 [ 0. -2.]]

B = [[1.]
 [1.]]

C = [[1. 0.]]

D = [[0.]]

Obtengamos la forma canónica observable:

In [45]:
ctrl.canonical_form(sys_o, 'observable')

(A = [[-3.  1.]
  [-2.  0.]]
 
 B = [[1.]
  [1.]]
 
 C = [[1. 0.]]
 
 D = [[0.]],
 matrix([[ 1., -0.],
         [ 2., -1.]]))

In [46]:
ctrl.canonical_form(sys_o, 'reachable')

ValueError: System not controllable to working precision.

Podemos ver que ahora no podemo obtener la forma canónica de obserbavilidad.

La razón de esto es que no se puee exitar el modo -1, que ahora quedó tapado desde el lado de la entrada. Toda excitación que tenga "frecuencia generalizada -1" será tapada por el cero en -1. Por lo tanto este sistema no es controlable, ya que no puede exitar desde esa entrada el modo -1.

Es importante destacar que ambos sistemas presentan la misma función tranferencia G1*G2, pero uno es solo controlable y el otro es solo observable. Esto se debe a que la controlabilidad y la observabilda son propiedades internas de un sistema, por lo que no pueden ser deciddidas a partir de modelos externos de un sistema como son las funciones transferencias.


Estas dos mismas pripiedades pueden ser analizadas con la forma modal. Tomemos el sistema $sys_C$ donde la entrada esta conectada a G1 y lasalida a G2:

In [47]:
ctrl.canonical_form(sys_c, 'modal')

(A = [[-1.  0.]
  [ 0. -2.]]
 
 B = [[ 1.41421356]
  [-1.        ]]
 
 C = [[ 0. -1.]]
 
 D = [[0.]],
 matrix([[0.70710678, 0.        ],
         [0.70710678, 1.        ]]))

Podemos ver que la matriz B tiene todos los valores distintos de 0. Esto significa que todos los modos están conectados a la entrada, por lo que deducimos que el sistema es controlable.

Pero podemos ver que C tiene un 0 en el primer elemento. Y que en la diagona de A el primer elemento es -1. Esto quiere decir que no hay niguna evidencia del modo -1 en la salida por que el sistema no es observable.

Probemos ahora con la segunda conexión:

In [48]:
ctrl.canonical_form(sys_o, 'modal')

(A = [[-1.  0.]
  [ 0. -2.]]
 
 B = [[0.        ]
  [1.41421356]]
 
 C = [[1.         0.70710678]]
 
 D = [[0.]],
 matrix([[1.        , 0.70710678],
         [0.        , 0.70710678]]))

Podemos ver ahora que la matriz C no tiene ningún valor igual a 0, por lo que ahora el sistema sería observable (todos los modos están presentes de alguna manera en la salida). Pero tenesmo un 0 en la primer fila de B, que se corresponde con el modo en -1. Esto quiere decir que no podemos excitar este modo. Por lo tanto no es controlable.